[workspace]
members = [
    "components/chainhook-sdk",
    "components/chainhook-cli",
    "components/chainhook-types-rs",
]
default-members = ["components/chainhook-cli", "components/chainhook-sdk"]
resolver = "2"

[patch.crates-io]
"jsonrpc" = { git = 'https://github.com/apoelstra/rust-jsonrpc', rev = "1063671f122a8985c1b7c29030071253da515839" }
stacks-rpc-client = { version = "2", git = "https://github.com/hirosystems/clarinet.git", branch = "chore/upgrade-clarity-vm" }
clarity-vm = { version = "2", default-features = false, git = "https://github.com/stacks-network/stacks-core.git", branch = "feat/clarity-wasm-next-bump-version", package = "clarity" }
